service: notes-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  createNote:
    handler: handler.createNote
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt NewResource.Arn
    events:
      - httpApi:
          path: /notes
          method: post
  updateNote:
    handler: handler.updateNote
    events:
      - httpApi:
          path: /notes/{id}
          method: put
  deleteNote:
    handler: handler.deleteNote
    events:
      - httpApi:
          path: /notes/{id}
          method: delete
  getAllNotes:
    handler: handler.getAllNotes
    events:
      - httpApi:
          path: /notes/{id}
          method: get

plugins:
  - serverless-iam-roles-per-function
# you can add CloudFormation resource templates here
resources:
  Resources:
    NewResource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S
        KeySchema:
          - AttributeName: notesId
            KeyType: HASH

  Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"
